#!/usr/bin/env python3
"""Regenerate conf/zoneopcodes.xml and conf/worldopcodes.xml from conf/opcodes.toml.

opcodes.toml is the canonical source. The XML files are an output format the
daemon's QXmlStreamReader still consumes — keep both in sync by always running
this after editing the TOML. CMake invokes it as a custom-command pre-build.

Usage:
  python3 tools/toml_to_xml.py conf/opcodes.toml conf/zoneopcodes.xml conf/worldopcodes.xml
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path


GENERATED_HEADER = (
    "<!-- @generated by tools/toml_to_xml.py from conf/opcodes.toml.\n"
    "     Edit opcodes.toml, not this file — your changes will be overwritten on next build. -->"
)


def date_legacy(iso: str | None) -> str | None:
    """Convert YYYY-MM-DD → MM/DD/YY for compatibility with the old XML format."""
    if not iso:
        return None
    parts = iso.split("-")
    if len(parts) == 3 and all(p.isdigit() for p in parts):
        yyyy, mm, dd = parts
        return f"{int(mm):02d}/{int(dd):02d}/{int(yyyy) % 100:02d}"
    return iso


def xml_attr(s: str) -> str:
    """Escape a string for use as an XML attribute value (double-quoted).

    Only `&`, `<`, and `"` strictly need escaping in a `"..."` attribute value;
    `>` is not special in XML 1.0 attribute values (matching the existing
    hand-written XML in this repo).
    """
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace('"', "&quot;"))


def xml_text(s: str) -> str:
    """Escape a string for use as XML element text.

    Per XML 1.0, only `&` and `<` strictly need escaping inside element content
    (`>` is fine outside the `]]>` CDATA-end sequence, which we don't emit).
    """
    return s.replace("&", "&amp;").replace("<", "&lt;")


def emit_xml(opcodes: list[dict]) -> str:
    out = ['<?xml version="1.0" encoding="UTF-8"?>']
    out.append('<!DOCTYPE seqopcodes SYSTEM "seqopcodes.dtd">')
    out.append(GENERATED_HEADER)
    out.append("<seqopcodes>")
    for op in opcodes:
        attrs = [f'id="{xml_attr(op["id"])}"', f'name="{xml_attr(op["name"])}"']
        if "updated" in op:
            attrs.append(f'updated="{xml_attr(date_legacy(op["updated"]))}"')
        if "implicitlen" in op:
            attrs.append(f'implicitlen="{xml_attr(op["implicitlen"])}"')
        # priority/priorityNote: load-ignored patch-day triage metadata (mirrors
        # Xerxes's legacy annotations). priority -1=dead/never-hunt, 0=inert,
        # 1..10=hunt-order after an id rotation; priority_note holds the reason.
        if "priority" in op:
            attrs.append(f'priority="{xml_attr(str(op["priority"]))}"')
        out.append(f"    <opcode {' '.join(attrs)}>")
        if "comment" in op:
            out.append(f"        <comment>{xml_text(op['comment'])}</comment>")
        if "priority_note" in op:
            out.append(f"        <priorityNote>{xml_text(op['priority_note'])}</priorityNote>")
        for p in op.get("payloads", []):
            out.append(
                f'        <payload dir="{xml_attr(p["dir"])}" '
                f'typename="{xml_attr(p["typename"])}" '
                f'sizechecktype="{xml_attr(p["sizechecktype"])}"/>'
            )
        out.append("    </opcode>")
    out.append("</seqopcodes>")
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print("usage: toml_to_xml.py opcodes.toml zoneopcodes.xml worldopcodes.xml", file=sys.stderr)
        return 2

    toml_path  = Path(argv[1])
    zone_path  = Path(argv[2])
    world_path = Path(argv[3])
    if not toml_path.exists():
        print(f"error: {toml_path} not found", file=sys.stderr)
        return 1

    with toml_path.open("rb") as f:
        data = tomllib.load(f)

    zone_ops  = data.get("zone", [])
    world_ops = data.get("world", [])

    zone_path.write_text(emit_xml(zone_ops))
    world_path.write_text(emit_xml(world_ops))
    print(f"wrote {zone_path} ({len(zone_ops)} opcodes) and "
          f"{world_path} ({len(world_ops)} opcodes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
