/* config.h — stub for extracted showeq-c sources.
 *
 * showeq-c is an autotools project; its `config.h` is generated by
 * ./configure and contains feature macros (HAVE_*) and PACKAGE/VERSION
 * strings. The daemon is a CMake project and the extracted code only
 * references `VERSION`, so this stub provides that plus a flag so future
 * code can tell it's running under the CMake build.
 */

#pragma once

#ifndef VERSION
#define VERSION "showeq-daemon"
#endif

#define SHOWEQ_DAEMON_BUILD 1
